// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/google/uuid"
)

type CreateDevice struct {
	Label string `json:"label"`
}

type Device struct {
	ID     uuid.UUID `json:"id"`
	Label  string    `json:"label"`
	Secret string    `json:"secret"`
}

type Query struct {
}
